added version string check.
ait-aecid/logdata-anomaly-miner pull request #1014
Opened 2021-12-28 14:15 UTC by dITySoftware

# Make sure these boxes are signed before submitting your Pull Request -- thank you.

# Must haves
- [x] I have read and followed the contributing guide lines at https://github.com/ait-aecid/logdata-anomaly-miner/wiki/Git-development-workflow
- [x] Issues exist for this PR
- [x] I added related issues using the "Fixes #<issue-id>"-notations
- [x] This Pull-Requests merges into the "development"-branch

Fixes #824 

# Submission specific

- [ ] This PR introduces breaking changes
- [ ] My change requires a change to the documentation
- [ ] I have updated the documentation accordingly
- [ ] I have added tests to cover my changes
- [ ] All new and existing tests passed

# Describe changes:
- Update the version string by running `sudo bash runReleaseStringCheck.sh -u`

2022-01-17 10:04 UTC, whotwagner requested changes

2022-01-17 10:04 UTC, whotwagner commented on aecid-testsuite/testFunctions.sh
> +  return 0
Comparing the versions won't work with our future version-strings because they can also include the "build-id" which is basically the git-commit-id. Here is an example of the new versionstrings: "2.5.0" or "2.5.0-49-g3f504579". Both will be possible

2022-01-17 10:09 UTC, dITySoftware commented on aecid-testsuite/testFunctions.sh
> +  return 0
I will extend the script for this use case.

2022-01-17 10:17 UTC, dITySoftware commented on aecid-testsuite/testFunctions.sh
> +  return 0
Basically in the second version only 2.5.0 should be extracted. Is this right? We are not interested in the "distance from tag" or "commit hash". Only when the version is newer, we override it with the whole version string.

v1.2.3-13-gabc1234
└────┤ └┤  └─────┴─ Short commit Hash (not the g)
     │  └─ Distance from tag
     └─ Latest Tag in Git

2022-01-17 10:55 UTC, whotwagner commented on aecid-testsuite/testFunctions.sh
> +  return 0
I would say that it is sufficient to check only 2.5.0

2022-01-26 19:09 UTC, dITySoftware commented on aecid-testsuite/testFunctions.sh
> +  return 0
I think the method is now working. Here are some examples which I have tested:
2.5.0 vs 2.5.0-49-g3f504579 -> 2.5.0
2.5.0 vs 2.4.0-49-g3f504579 -> 2.5.0
2.5.0 vs 2.6.0-49-g3f504579 -> 2.6.0-49-g3f504579
2.5.0 vs 2.5.1-49-g3f504579 -> 2.5.1-49-g3f504579
2.5.2 vs 2.5.2-49-g3f504579 -> nothing happens, because the algorithm thinks these versions are the same.
2.5.11 vs 2.5.10-49-g3f504579 -> 2.5.11
2.5.2 vs 2.5.10-49-g3f504579 -> 2.5.10-49-g3f504579

2022-02-15 09:24 UTC, whotwagner approved these changes

2022-02-15 09:24 UTC, merged