Fix performance dependencies
ait-aecid/logdata-anomaly-miner pull request #1050
Opened 2022-02-26 18:31 UTC by dITySoftware

… TryItOut).

# Make sure these boxes are signed before submitting your Pull Request -- thank you.

# Must haves
- [x] I have read and followed the contributing guide lines at https://github.com/ait-aecid/logdata-anomaly-miner/wiki/Git-development-workflow
- [x] Issues exist for this PR
- [x] I added related issues using the "Fixes #<issue-id>"-notations
- [x] This Pull-Requests merges into the "development"-branch

Fixes #1049 

# Submission specific

- [ ] This PR introduces breaking changes
- [ ] My change requires a change to the documentation
- [ ] I have updated the documentation accordingly
- [ ] I have added tests to cover my changes
- [ ] All new and existing tests passed

# Describe changes:
-

2022-03-04 18:31 UTC, whotwagner requested changes

2022-03-04 18:31 UTC, whotwagner commented on aecid-testsuite/Dockerfile
> +    && chown aminer.aminer -R /var/lib/aminer && chown aminer.aminer -R /etc/aminer
Aminer does not need write-access at /etc/aminer therefore we should prefer owner root.root for /etc/aminer and handle access with world permissions

2022-03-04 18:55 UTC, dITySoftware commented on aecid-testsuite/Dockerfile
> +    && chown aminer.aminer -R /var/lib/aminer && chown aminer.aminer -R /etc/aminer
Could you please write the permissions I need to set with chmod to achieve this?
Testing the Wiki pages, the scripts actually need write access to /etc/aminer to write the config files from the scripts.
How should this be handled?
I could of course just change the path with sed or another tool.

2022-03-08 06:09 UTC, dITySoftware commented on aecid-testsuite/Dockerfile
> +    && chown aminer.aminer -R /var/lib/aminer && chown aminer.aminer -R /etc/aminer
Should I change the path in the wiki scripts or how should we solve this?

2022-03-09 09:24 UTC, whotwagner commented on aecid-testsuite/Dockerfile
> +    && chown aminer.aminer -R /var/lib/aminer && chown aminer.aminer -R /etc/aminer
why not using sudo to write the config-files?

2022-03-10 07:09 UTC, dITySoftware commented on aecid-testsuite/Dockerfile
> +    && chown aminer.aminer -R /var/lib/aminer && chown aminer.aminer -R /etc/aminer
Unfortunately there is no read access into the directory. Running following commands locally proves that it does not work


This is also not possible, because all of the packages are also linked in /etc/aminer/conf-enabled. In aminer-ansible these are automatically linked there https://github.com/ait-aecid/aminer-ansible/blob/main/tasks/main.yml. For example: 
```
- name: Link scipy                         
  file:                                    
    src: "{{aminer_pythonpath}}/scipy"     
    dest: /etc/aminer/conf-enabled/scipy   
    state: link  
```
So basically the linking in logdata-anomaly-miner/Dockerfile are wrong:
```
RUN ln -s /usr/lib/logdata-anomaly-miner/aminerremotecontrol.py /usr/bin/aminerremotecontrol \
	&& ln -s /usr/lib/logdata-anomaly-miner/aminer.py /usr/bin/aminer \
	&& chmod 0755 /usr/lib/logdata-anomaly-miner/aminer.py  \
	&& chmod 0755 /usr/lib/logdata-anomaly-miner/aminerremotecontrol.py \
	&& ln -s /usr/lib/python3/dist-packages/kafka /usr/lib/logdata-anomaly-miner/kafka \
	&& ln -s /usr/lib/python3/dist-packages/cerberus /usr/lib/logdata-anomaly-miner/cerberus \
	&& ln -s /usr/lib/python3/dist-packages/scipy /usr/lib/logdata-anomaly-miner/scipy \
	&& ln -s /usr/lib/python3/dist-packages/numpy /usr/lib/logdata-anomaly-miner/numpy \
	&& ln -s /usr/lib/python3/dist-packages/pkg_resources /usr/lib/logdata-anomaly-miner/pkg_resources \
	&& ln -s /usr/lib/python3/dist-packages/yaml /usr/lib/logdata-anomaly-miner/yaml \
	&& ln -s /usr/lib/python3/dist-packages/pytz /usr/lib/logdata-anomaly-miner/pytz \
	&& ln -s /usr/lib/python3/dist-packages/dateutil /usr/lib/logdata-anomaly-miner/dateutil \
	&& ln -s /usr/lib/python3/dist-packages/six.py /usr/lib/logdata-anomaly-miner/six.py \
	&& ln -s /usr/lib/python3/dist-packages/urllib3 /usr/lib/logdata-anomaly-miner/urllib3 \
	&& ln -s /usr/lib/python3/dist-packages/statsmodels /usr/lib/logdata-anomaly-miner/statsmodels \
	&& groupadd -g $GID -o $UNAME && useradd -u $UID -g $GID -ms /usr/sbin/nologin $UNAME && mkdir -p /var/lib/aminer/logs && mkdir /etc/aminer \
    && chown $UID.$GID -R /var/lib/aminer \
    && chown $UID.$GID -R /docs \
    && chmod 0755 /aminerwrapper.sh
```
These should all link to /etc/aminer/conf-enabled.
I will look into that.

2022-03-10 12:59 UTC, whotwagner commented on aecid-testsuite/Dockerfile
> +    && chown aminer.aminer -R /var/lib/aminer && chown aminer.aminer -R /etc/aminer
Something is different in your example:

```
sudo chown -R root:root /etc/aminer
sudo ls -la /etc/aminer
total 44
drwxr-x---   4 root root  4096 Mär 10 07:12 .
drwxr-xr-x 153 root root 12288 Mär 10 07:26 ..
drwxrwxr-x   5 root root  4096 Feb 21 14:59 conf-available
drwxrwxr-x   3 root root  4096 Feb 28 16:45 conf-enabled
-rw-r--r--   1 root root   407 Mär 10 07:13 config.yml
-rw-rw-r--   1 root root  4868 Feb 28 21:30 template_config.py
-rw-rw-r--   1 root root  4909 Feb 28 21:30 template_config.yml
sudo aminer -c /etc/aminer/config.yml
aminer: config "/etc/aminer/config.yml" not (yet) available!
aminer: Analysis child process 40109 terminated unexpectedly with signal 0x100
```

As you can see, /etc/aminer is not readable by world:

```
drwxr-x---   4 root root  4096 Mär 10 07:12 .
```

I started a "naked" aecid-testing-container:

```
docker run --rm -it aecid/logdata-anomaly-miner-testing SHELL
```

As you can see the directory /etc/aminer is readable in such a container:

```
aminer@b81b3b61b188:~/aecid-testsuite$ sudo ls -ld /etc/aminer
drwxr-xr-x 4 root root 4096 Mar 10 13:55 /etc/aminer
```

How comes that in your example the permissions of /etc/aminer are not "drwxr-xr-x"?

2022-03-11 09:17 UTC, dITySoftware commented on aecid-testsuite/Dockerfile
> +    && chown aminer.aminer -R /var/lib/aminer && chown aminer.aminer -R /etc/aminer
I think this is because of some differences in my local installation.
Using your tips, I have changed the permissions of /etc/aminer to 0755 and always used sudo when writing to some files in there. This works fine.

2022-03-11 11:53 UTC, whotwagner approved these changes

2022-03-11 11:53 UTC, merged