239 replace deepsource with open source components
ait-aecid/logdata-anomaly-miner pull request #1309
Opened 2024-03-25 16:17 UTC by ernstleierzopf

# Make sure these boxes are signed before submitting your Pull Request -- thank you.

# Must haves
- [ ] I have read and followed the contributing guide lines at https://github.com/ait-aecid/logdata-anomaly-miner/wiki/Git-development-workflow
- [ ] Issues exist for this PR
- [ ] I added related issues using the "Fixes #<issue-id>"-notations
- [ ] This Pull-Requests merges into the "development"-branch

Fixes #1305 

# Submission specific

- [ ] This PR introduces breaking changes
- [ ] My change requires a change to the documentation
- [ ] I have updated the documentation accordingly
- [ ] I have added tests to cover my changes
- [ ] All new and existing tests passed

# Describe changes:
-

2024-03-28 12:09 UTC, whotwagner requested changes

2024-03-28 12:41 UTC, ernstleierzopf commented on docs/images/aminer-config-color.drawio
> -<mxfile host="app.diagrams.net" modified="2021-02-18T11:42:53.841Z" agent="5.0 (X11)" etag="3rjyfRs_-Es_vVYdd4aE" version="14.4.2" type="device"><diagram id="5UVBhFNdrDuveJu0V3Pm" name="Page-1">7Zpbj
newline was added as a result of the pre-commit hook.
I ran the pre-commit on all files, so no issues will happen in future commits.

2024-04-29 10:53 UTC, ernstleierzopf commented on .pre-commit-config.yaml
done

2024-04-29 11:05 UTC, ernstleierzopf commented on aecid-testsuite/runFlake8.sh
> +python3 -m flake8 --max-line-length=140 --exclude=aecid-testsuite/ /usr/lib/logdata-anomaly-miner
done

2024-04-29 11:16 UTC, ernstleierzopf commented on source/root/usr/lib/logdata-anomaly-miner/aminer.py
> +            except KeyError:
This is the only exception I would expect. The error message (which is unchanged) only explains this error as the user or group name could not be resolved. Other errors will fail the aminer anyways and should either be returned as they are or they should be catched explicitly.

I see nothing that could go wrong with this approach, as the program quits anyways.

2024-04-29 11:37 UTC, ernstleierzopf commented on .pre-commit-config.yaml
> --   repo: https://gitlab.com/pycqa/flake8
I add this to the Jenkinsfile as an test which produces output, but it does not fail the pipeline. We did not fix the complexity thing and running the tests through would not be possible any more.

2024-04-29 14:14 UTC, ernstleierzopf commented on .pre-commit-config.yaml
> --   repo: https://gitlab.com/pycqa/flake8
also checked and added other plugins from flake8.

2024-08-01 11:52 UTC, whotwagner approved these changes

2024-08-01 11:52 UTC, merged