added the ETD and VTD and unittests for them.
ait-aecid/logdata-anomaly-miner pull request #142
Opened 2020-08-19 09:36 UTC by dITySoftware

2020-08-19 12:01 UTC, 4cti0nfi9ure commented
Please remove ContinuousSampleGenerator.py and the possibility to generate new datasets for each test run. Unittests have to be deterministic.

2020-08-19 13:44 UTC, dITySoftware commented
These tests are actually using fixed data from unit/data/vtd_data if the generate_data_sets flag, which is available in every test generating data, is False (which is the default case).

Generating data dynamically might come in handy for manual test runs, when changes are made in the VTD.

I see no need for changing the tests, but can make them if needed.

2020-08-26 11:14 UTC, 4cti0nfi9ure requested changes
ETD and VTD require major changes.

2020-08-26 11:14 UTC, 4cti0nfi9ure commented on aecid-testsuite/unit/analysis/VariableTypeDetectorTest.py
> +    '''def test3detect_continuous_shape_random_data(self):
Remove all tests that are capable of generatring data sets.

2020-08-26 11:17 UTC, dITySoftware commented on .travis.yml
> +  - sudo pip3 install -U scipy
scipy needs to be updated to a newer version. Otherwise an error is occuring.

2020-10-06 07:43 UTC, dITySoftware commented on aecid-testsuite/unit/analysis/EventCorrelationDetectorTest.py
> +        set_random_seed(42)
the last line sets the random seed of the ECD.

2020-10-06 09:36 UTC, landauermax approved these changes
Looks good to me

2020-10-06 09:46 UTC, 4cti0nfi9ure approved these changes

2020-10-06 09:47 UTC, merged