fixed AMinerRemoteControl and adapted aminerRemoteControlDemo.sh.
ait-aecid/logdata-anomaly-miner pull request #148
Opened 2020-09-06 17:35 UTC by dITySoftware

2020-09-29 12:45 UTC, whotwagner requested changes
Please provide comments for the methods in class AMinerRemoteControlExecutionMethods

2020-09-29 12:45 UTC, whotwagner commented on source/root/usr/lib/logdata-anomaly-miner/aminer/AMinerRemoteControlExecutionMethods.py
> +def repr_recursive(attr):
please comment this function

2020-09-29 12:45 UTC, whotwagner commented on source/root/usr/lib/logdata-anomaly-miner/aminer/AMinerRemoteControlExecutionMethods.py
> +def reformat_attr(attr):
please comment this function

2020-09-29 19:05 UTC, dITySoftware commented on source/root/usr/lib/logdata-anomaly-miner/aminer/AMinerRemoteControlExecutionMethods.py
> +def repr_recursive(attr):
This method is actually not for public use, but it does not belong to the AMinerRemoteControlMethods class directly. I have commented these methods and all other public methods.

For better indication these methods now start with _.

2020-09-29 19:05 UTC, dITySoftware commented on source/root/usr/lib/logdata-anomaly-miner/aminer/AMinerRemoteControlExecutionMethods.py
> +def reformat_attr(attr):
see upper comment.

2020-09-30 08:47 UTC, whotwagner commented on source/root/usr/lib/logdata-anomaly-miner/aminer/AMinerRemoteControlExecutionMethods.py
> +def _reformat_attr(attr):
Is there a reason why we do not use json.JSONEncoder here? We could customize the JSONEncoder by inheriting from it.

2020-09-30 11:41 UTC, dITySoftware commented on source/root/usr/lib/logdata-anomaly-miner/aminer/AMinerRemoteControlExecutionMethods.py
> +def _reformat_attr(attr):
Basic data types like strings or integers can be encoded by the JSONEncoder. Due to the complexity of the configuration it would not be possible to create the functionality with much less code.

2020-09-30 11:54 UTC, whotwagner approved these changes

2020-09-30 11:55 UTC, merged