implemented the --Clear parameter.
ait-aecid/logdata-anomaly-miner pull request #153
Opened 2020-09-24 08:23 UTC by dITySoftware

2020-09-28 13:09 UTC, whotwagner commented on source/root/usr/lib/logdata-anomaly-miner/AMiner
> +                    sys.exit(1)
do we really have to exit here or is it possible to make it more fault tolerant?

2020-09-28 13:31 UTC, whotwagner requested changes

2020-09-28 13:31 UTC, whotwagner commented on source/root/usr/lib/logdata-anomaly-miner/AMiner
> +        if arg_name == '--Clear':
We need another Flag "--FromBegin" that deletes just the AnalysisChild

2020-09-28 13:31 UTC, whotwagner commented on source/root/usr/lib/logdata-anomaly-miner/AMiner
> +        if remove_persistence_dirs is not None:
Please make sure that Clear does not delete the AnalysisChild

2020-09-28 13:31 UTC, whotwagner commented on source/root/usr/lib/logdata-anomaly-miner/AMiner
> +            remove_persistence_dirs = remove_persistence_dirs.rstrip(']').lstrip('[').split(',')
We would prefer to make it more simpler without brackets "[ and ]" and please make sure that directory traversal is not possible

2020-09-28 14:01 UTC, dITySoftware commented on source/root/usr/lib/logdata-anomaly-miner/AMiner
> +                    sys.exit(1)
the aminer persistence directory should not contain files, only directories. There is a chance that the user has chosen a wrong directory. We could continue, but it is risky for the user.

2020-09-28 14:29 UTC, dITySoftware commented on source/root/usr/lib/logdata-anomaly-miner/AMiner
> +            remove_persistence_dirs = remove_persistence_dirs.rstrip(']').lstrip('[').split(',')
Done.

2020-09-28 14:32 UTC, dITySoftware commented on source/root/usr/lib/logdata-anomaly-miner/AMiner
> +        if remove_persistence_dirs is not None:
It does not.

2020-09-28 14:49 UTC, dITySoftware commented on source/root/usr/lib/logdata-anomaly-miner/AMiner
> +        if arg_name == '--Clear':
I have implemented it.

2020-09-29 11:11 UTC, whotwagner requested changes

2020-09-29 11:22 UTC, dITySoftware commented on source/root/usr/lib/logdata-anomaly-miner/AMiner
> +            print('The --Config and --Remove arguments must not be used together!', file=sys.stderr)
yes we do. That was only a typo. --Clear was meant.

2020-09-29 11:26 UTC, dITySoftware commented on source/root/usr/lib/logdata-anomaly-miner/AMiner
> +            remove_persistence_dirs.append(sys.argv[arg_pos])
added checks in lines 175-177.

2020-09-29 11:27 UTC, dITySoftware commented on source/root/usr/lib/logdata-anomaly-miner/AMiner
> +            except Exception as e:
changed that to continue.

2020-09-29 11:32 UTC, dITySoftware commented on source/root/usr/lib/logdata-anomaly-miner/AMiner
> +                    sys.exit(1)
Changed the AMiner to continue instead.

2020-09-29 12:32 UTC, whotwagner requested changes

2020-09-29 12:32 UTC, whotwagner commented on source/root/usr/lib/logdata-anomaly-miner/AMiner
> +            except Exception as e:
Please specify what Exception you do expect

2020-09-29 12:32 UTC, whotwagner commented on source/root/usr/lib/logdata-anomaly-miner/AMiner
> +            except Exception as e:
Please specify what Exception you do expect(in line 235)

2020-09-29 14:44 UTC, dITySoftware commented on source/root/usr/lib/logdata-anomaly-miner/AMiner
> +            except Exception as e:
shutil.rmtree actually raises an "Exception" when calling os.lstat and os.open. There is no more specific exception raised. Therefor "Exception" has to be catched here.

2020-09-29 14:44 UTC, dITySoftware commented on source/root/usr/lib/logdata-anomaly-miner/AMiner
> +            except Exception as e:
same as above

2020-09-30 08:13 UTC, whotwagner requested changes

2020-09-30 08:13 UTC, whotwagner commented on source/root/usr/lib/logdata-anomaly-miner/AMiner
> +            except Exception as e:
os.lstat and os.open raise OSError( https://docs.python.org/3/library/os.html ) so I believe that shutil.rmtree also raises OSError.

2020-09-30 10:54 UTC, dITySoftware commented on source/root/usr/lib/logdata-anomaly-miner/AMiner
> +            except Exception as e:
Changed now.

2020-09-30 10:56 UTC, whotwagner approved these changes

2020-09-30 11:28 UTC, merged