added components to the yaml config.
ait-aecid/logdata-anomaly-miner pull request #165
Opened 2020-09-28 10:48 UTC by dITySoftware

… config.

2020-10-16 14:38 UTC, whotwagner requested changes
In addition I sent you an Email with another big change-request

2020-10-17 08:29 UTC, dITySoftware commented on .travis.yml
> +  - sudo ln -s /usr/lib/python3.6/site-packages/cerberus /etc/aminer/conf-enabled/
removed links for cerberus scipy and numpy as they are in the ansible role.

2020-10-17 08:33 UTC, dITySoftware commented on aecid-testsuite/runAMinerDemo.sh
> +    exit 2
aminerDemo.sh only has two exit codes: 0 - success, 1 - failure.
Therfor it is clear what exit code 2 means. Is it necessary to echo an error message here?

These exit codes just signal Travis to fail. The scripts are not thought to be used by users.

2020-10-17 08:40 UTC, dITySoftware commented on aecid-testsuite/unit/data/configfiles/template_config.yml
> +          auto_include_flag: True
i refactored it to learn_mode as we are using snake mode for everything now. Is that OK?

2020-10-17 08:47 UTC, dITySoftware commented on aecid-testsuite/unit/config/YamlConfigTest.py
> +        aminer_config.load_yaml('unit/data/configfiles/apache_inline_config.yml')
renamed all apache configs to multiple_components.

2020-10-17 08:55 UTC, dITySoftware commented on aecid-testsuite/unit/config/YamlConfigTest.py
> +        aminer_config.load_yaml('unit/data/configfiles/apache_inline_config_null_event_handlers.yml')
yes it is nessecary to load the config. However it is possible to delete one config and just remove 'EventHandlers' or 'Analysis' from the dictionary and reload the context. I have done that in commit 39bdf0e716709c7947fbcb94beb3f674a6d6793a.

2020-10-17 09:04 UTC, dITySoftware commented on source/root/usr/lib/logdata-anomaly-miner/aminer/ymlconfig.py
> +                if item['type'].name == 'KafkaEventHandler':
I have deleted it as most of the code is deprecated (for example args is no longer used).

I readded the code and change variables like learnMode to snake case.
Kafka is not tested yet. This needs to be done in future pull requests.

2020-10-17 09:07 UTC, dITySoftware commented on source/root/usr/lib/logdata-anomaly-miner/aminer/ymlconfig.py
> +                    ctx = JsonConverterHandler([ctx], analysis_context)
no we can not. I have changed the order of the code, so the None check is performed before.

2020-10-17 09:16 UTC, dITySoftware commented on aecid-testsuite/unit/config/YamlConfigTest.py
>          spec = importlib.util.spec_from_file_location('aminer_config', '/usr/lib/logdata-anomaly-miner/aminer/ymlconfig.py')
I have actually changed the code like with 'EventHandlers' to not load a second config, but just deleting the entry in the aminer_config.yaml_data and reloading the context.

2020-10-17 09:21 UTC, dITySoftware commented on source/root/usr/lib/logdata-anomaly-miner/aminer/ymlconfig.py
> +            elif item['type'].name == 'MatchPathFilter':
template_config.py also does not contain all components. I think that is not the purpose of the template_config.
test17 covers the loading of the demo-config.py and demo-config.yml, which should be the same, and compared the contexts.

demo-config.yml contains all of the components.

Please confirm once again that the template_config also should contain all components.

2020-10-20 06:57 UTC, landauermax commented on aecid-testsuite/unit/data/configfiles/template_config.yml
> +          auto_include_flag: True
I would say yes, it is ok in snake_case.

2020-10-29 13:28 UTC, whotwagner requested changes

2020-10-29 13:28 UTC, whotwagner commented on source/root/usr/lib/logdata-anomaly-miner/aminer/ymlconfig.py
> +            elif item['type'].name == 'MatchPathFilter':
Good idea. Please make a comment in template_config.yml with a reference to demo-config.yml

2020-10-29 14:15 UTC, dITySoftware commented on source/root/usr/lib/logdata-anomaly-miner/aminer/ymlconfig.py
> +            elif item['type'].name == 'MatchPathFilter':
Done.

2020-10-30 10:58 UTC, whotwagner requested changes
Just waiting for fixed travis-Issues

2020-11-02 09:34 UTC, whotwagner approved these changes

2020-11-02 09:35 UTC, merged