Suspend mode
ait-aecid/logdata-anomaly-miner pull request #195
Opened 2020-10-16 09:42 UTC by dITySoftware

2020-10-29 14:10 UTC, whotwagner requested changes

2020-10-29 14:10 UTC, whotwagner commented on aecid-testsuite/demo/AMinerRemoteControl/aminerRemoteControlDemo.sh
> +
Could you create a test that checks if the aminer really doesn't do anything(chaning the persistency) and continues at the logline where it stopped previously.

2020-10-29 18:20 UTC, dITySoftware commented on aecid-testsuite/demo/AMinerRemoteControl/aminerRemoteControlDemo.sh
> +
I have created a test runSuspendModeTest.sh.
It does not test if the persistence data is not changed. However I am 100% sure no data is persisted.
Only when the analysis loop is left in suspend mode the data is persisted before the process is shutdown.

2020-10-29 21:01 UTC, dITySoftware commented on aecid-testsuite/demo/AMinerRemoteControl/aminerRemoteControlDemo.sh
> +
i have now added persistence tests to runSuspendModeTest.sh.
also implemented Core.PersistencePeriod parameter.

2020-11-18 09:36 UTC, whotwagner approved these changes

2020-11-18 09:36 UTC, merged