Stat and Debug output
ait-aecid/logdata-anomaly-miner pull request #205
Opened 2020-10-22 08:43 UTC by dITySoftware

2020-11-02 12:15 UTC, whotwagner requested changes

2020-11-02 12:15 UTC, whotwagner commented on source/root/usr/lib/logdata-anomaly-miner/aminer.py
> +    AMinerConfig.DEBUG_LEVEL = debug_level
if neither --debug nor --stat was used, the STAT/DEBUG-LEVEL woult overwritten anyway.

2020-11-02 12:15 UTC, whotwagner commented on source/root/usr/lib/logdata-anomaly-miner/aminer.py
> +                    str(debug_level)]
Do we also need the daemon-flag here?

2020-11-02 12:15 UTC, whotwagner commented on source/root/usr/lib/logdata-anomaly-miner/aminer/AMinerConfig.py
> +    with open(REMOTE_CONTROL_LOG_FILE, "r") as logFile:
what happens if the logfile is not readable?

2020-11-02 12:20 UTC, dITySoftware commented on source/root/usr/lib/logdata-anomaly-miner/aminer.py
> +        stat_file_handler = logging.FileHandler('/tmp/statistics.log')
I have removed the else block. I think it actually can't occur, because the program would exit before even starting, when the persistence directory does not exist.

2020-11-02 12:23 UTC, dITySoftware commented on source/root/usr/lib/logdata-anomaly-miner/aminer.py
> +        stat_file_handler = logging.FileHandler(os.path.join(persistence_dir, 'statistics.log'))
It is expected that the file does not exist and the persistence_dir is writeable. So there is no problem in creating a new file. Changing the permissions would happen on purpose and would probably lead to an OSError.

2020-11-02 12:25 UTC, dITySoftware commented on source/root/usr/lib/logdata-anomaly-miner/aminer.py
> +    AMinerConfig.DEBUG_LEVEL = debug_level
That's true. However it is overwritten by the default levels. Is that problematic?

2020-11-02 12:27 UTC, dITySoftware commented on source/root/usr/lib/logdata-anomaly-miner/aminer.py
> +                    str(debug_level)]
No. The process was at this point already forked. --Stat and --Debug are needed as the modules are somehow reloaded and the AMinerConfig Variables would be set to the default level.

2020-11-02 12:41 UTC, dITySoftware commented on source/root/usr/lib/logdata-anomaly-miner/aminer/AMinerConfig.py
> +    with open(REMOTE_CONTROL_LOG_FILE, "r") as logFile:
save_config is only called via remote control. In the worst case there is an OSError which is then sent as text output to the remote control user. Nothing happens to the main aminer instance.

2020-11-02 13:31 UTC, whotwagner requested changes

2020-11-02 13:31 UTC, whotwagner commented on source/root/usr/lib/logdata-anomaly-miner/aminer.py
> +        stat_file_handler = logging.FileHandler(os.path.join(persistence_dir, 'statistics.log'))
I believe we should catch that error and write a proper error-message

2020-11-02 13:31 UTC, whotwagner commented on source/root/usr/lib/logdata-anomaly-miner/aminer.py
> +    AMinerConfig.DEBUG_LEVEL = debug_level
What happens if the user does not use any parameters for the levels, but configured the levels in the configuration-file? I think the configuration of the user will be overruled by the default-values.

2020-11-02 13:31 UTC, whotwagner commented on source/root/usr/lib/logdata-anomaly-miner/aminer/AMinerConfig.py
> +    with open(REMOTE_CONTROL_LOG_FILE, "r") as logFile:
we should catch that error and write a proper error-message.

2020-11-02 13:35 UTC, dITySoftware commented on source/root/usr/lib/logdata-anomaly-miner/aminer.py
> +    AMinerConfig.DEBUG_LEVEL = debug_level
currently it is not possible to set these values in the config files.

2020-11-02 14:06 UTC, dITySoftware commented on source/root/usr/lib/logdata-anomaly-miner/aminer.py
> +        stat_file_handler = logging.FileHandler(os.path.join(persistence_dir, 'statistics.log'))
added an error message.

2020-11-02 14:06 UTC, dITySoftware commented on source/root/usr/lib/logdata-anomaly-miner/aminer/AMinerConfig.py
> +    with open(REMOTE_CONTROL_LOG_FILE, "r") as logFile:
added an error message.

2020-11-02 14:18 UTC, dITySoftware commented on source/root/usr/lib/logdata-anomaly-miner/aminer.py
> +    AMinerConfig.DEBUG_LEVEL = debug_level
added the functionality

2020-11-02 14:18 UTC, dITySoftware commented
Fixes #221

2020-11-02 15:01 UTC, dITySoftware commented
I have completely changed the handling of the files. They are now located in the persistence dir and the permissions are set to the aminer user and aminer group.

2020-11-02 18:59 UTC, whotwagner requested changes
Maybe I missed it, but I haven found proper tests that make sure that logging(cli-params, ymlconfig, aso.) works as expected. I am fine if we create another PR for that

2020-11-02 18:59 UTC, whotwagner commented on source/root/usr/lib/logdata-anomaly-miner/aminer/schema.py
> +        'Log.StatisticsPeriod': {
We should also make the logfiles(full path to stats and debug) configurable.

2020-11-03 07:56 UTC, dITySoftware commented on source/root/usr/lib/logdata-anomaly-miner/aminer/schema.py
> +        'Log.StatisticsPeriod': {
> Maybe I missed it, but I haven found proper tests that make sure that logging(cli-params, ymlconfig, aso.) works as expected. I am fine if we create another PR for that

Most error messages are tested in the classes themselves. As logging is initiated in the main aminer processes, the logging does not work as inteded in unittests. However that is to be expected.

ymlconfig should be covered by the YamlConfigTest or is something missing?

Currently statistics, which are implemented with logs, are tested seperately. Is it actually needed to test RemoteControl logs and Debug logs as integration test?

2020-11-03 07:58 UTC, dITySoftware commented on source/root/usr/lib/logdata-anomaly-miner/aminer/schema.py
> +        'Log.StatisticsPeriod': {
> We should also make the logfiles(full path to stats and debug) configurable.

I have added a new issue.

2020-11-03 13:48 UTC, dITySoftware commented
Fixes #149

2020-11-03 13:49 UTC, dITySoftware commented
Fixes #91.

2020-11-05 12:05 UTC, dITySoftware commented
Fixes #222

2020-11-13 18:30 UTC, merged