Fixed a bug related to the persistency and event types which have no …
ait-aecid/logdata-anomaly-miner pull request #299
Opened 2020-11-18 15:49 UTC by hoeldg

# Make sure these boxes are signed before submitting your Pull Request -- thank you.

# Must haves
- [x] I have read and followed the contributing guide lines at https://github.com/ait-aecid/logdata-anomaly-miner/wiki/Git-development-workflow
- [x] Issues exist for this PR
- [x] I added related issues using the "Fixes #123'-notations
- [x] This Pull-Requests merges into the "development"-branch

# Submission specific

- [ ] This PR introduces breaking changes
- [ ] My change requires a change to the documentation
- [ ] I have updated the documentation accordingly
- [ ] I have added tests to cover my changes
- [x] All new and existing tests passed

# Describe changes:
-
-
-

2020-11-18 16:00 UTC, dITySoftware requested changes
I have run the test once again. It does not solve the issue. Travis will be without errors, however the issue is not solved.

2020-11-18 16:05 UTC, dITySoftware commented
> I have run the test once again. It does not solve the issue. Travis will be without errors, however the issue is not solved.

Sorry my bad. Did not see the changes in ETD. Works now.

2020-11-18 16:05 UTC, dITySoftware approved these changes

2020-11-19 09:10 UTC, landauermax approved these changes
Looks good to me

2020-11-19 09:10 UTC, merged