057 rewrite decimal float value model element unittests
ait-aecid/logdata-anomaly-miner pull request #578
Opened 2021-03-24 07:04 UTC by dITySoftware

# Make sure these boxes are signed before submitting your Pull Request -- thank you.

# Must haves
- [x] I have read and followed the contributing guide lines at https://github.com/ait-aecid/logdata-anomaly-miner/wiki/Git-development-workflow
- [x] Issues exist for this PR
- [x] I added related issues using the "Fixes #123'-notations
- [x] This Pull-Requests merges into the "development"-branch

Fixes #529

# Submission specific

- [ ] This PR introduces breaking changes
- [ ] My change requires a change to the documentation
- [ ] I have updated the documentation accordingly
- [ ] I have added tests to cover my changes
- [ ] All new and existing tests passed

# Describe changes:
- rewrote unittests for DecimalFloatValueME

2021-03-29 08:56 UTC, whotwagner requested changes

2021-03-29 08:56 UTC, whotwagner commented on source/root/usr/lib/logdata-anomaly-miner/aminer/parsing/DecimalFloatValueModelElement.py
> +        if self.pad_characters == b"" and data.startswith(b"0") and not data.startswith(b"0."):
Add test if a number follows

2021-03-29 09:19 UTC, dITySoftware commented on source/root/usr/lib/logdata-anomaly-miner/aminer/parsing/DecimalFloatValueModelElement.py
> +        if self.pad_characters == b"" and data.startswith(b"0") and not data.startswith(b"0."):
i have changed that and added unittests.

2021-04-06 09:06 UTC, landauermax approved these changes
Looks good to me

2021-04-06 09:09 UTC, whotwagner approved these changes

2021-04-06 09:09 UTC, merged