Feature entropydetector
ait-aecid/logdata-anomaly-miner pull request #776
Opened 2021-07-01 13:37 UTC by landauermax

# Make sure these boxes are signed before submitting your Pull Request -- thank you.

# Must haves
- [X] I have read and followed the contributing guide lines at https://github.com/ait-aecid/logdata-anomaly-miner/wiki/Git-development-workflow
- [X] Issues exist for this PR
- [X] I added related issues using the "Fixes #<issue-id>"-notations
- [X] This Pull-Requests merges into the "development"-branch

Fixes #403 

# Submission specific

- [ ] This PR introduces breaking changes
- [X] My change requires a change to the documentation
- [X] I have updated the documentation accordingly
- [X] I have added tests to cover my changes
- [ ] All new and existing tests passed

# Describe changes:
- Add entropy detector

2021-07-01 15:15 UTC, 4cti0nfi9ure commented on aecid-testsuite/unit/analysis/EntropyDetectorTest.py
> +        m_2 = MatchElement('/value', b'logdata-anomaly-miner', b'logdata-anomaly-miner', None)
In the comment above the second element is aecid.

2021-07-01 15:27 UTC, 4cti0nfi9ure requested changes
Please address the comment.

2021-07-02 06:15 UTC, landauermax commented on aecid-testsuite/unit/analysis/EntropyDetectorTest.py
> +        m_2 = MatchElement('/value', b'logdata-anomaly-miner', b'logdata-anomaly-miner', None)
I fixed it.

2021-07-02 09:02 UTC, 4cti0nfi9ure approved these changes

2021-07-02 09:02 UTC, merged