Created docker-compose (#807)
ait-aecid/logdata-anomaly-miner pull request #826
Opened 2021-07-16 16:59 UTC by prajeshpradhan

# Make sure these boxes are signed before submitting your Pull Request -- thank you.

# Must haves
- [x] I have read and followed the contributing guide lines at https://github.com/ait-aecid/logdata-anomaly-miner/wiki/Git-development-workflow
- [x] Issues exist for this PR
- [x] I added related issues using the "Fixes #<issue-id>"-notations
- [x] This Pull-Requests merges into the "development"-branch

Fixes #807 

# Submission specific

- [ ] This PR introduces breaking changes
- [x] My change requires a change to the documentation
- [ ] I have updated the documentation accordingly
- [ ] I have added tests to cover my changes
- [ ] All new and existing tests passed

# Describe changes:
- Created a docker-compose file

2021-07-21 09:11 UTC, whotwagner requested changes

2021-07-21 09:11 UTC, whotwagner commented on docker-compose.yml
> +        command: ["aminer", "--version"]
Please remove the command since we don't want to override the default( yet)

2021-07-23 08:53 UTC, dITySoftware commented
Please fetch the ait:development Branch into prajeshpradhan:create-docker-compose. You can do that by going to [https://github.com/prajeshpradhan/logdata-anomaly-miner/tree/create-docker-compose](https://github.com/prajeshpradhan/logdata-anomaly-miner/tree/create-docker-compose) and clicking "Fetch upstream" (right under the Code download button) -> Open Pull Request -> change ait:main to ait:development -> Merge

Thanks.

2021-07-27 10:22 UTC, whotwagner approved these changes
Nice work. Thank you very much for contributing to logdata-anomaly-miner. Please keep on contributing, your work is appreciated

2021-07-27 10:22 UTC, merged