added RotatingFileHandlers for loggers.
ait-aecid/logdata-anomaly-miner pull request #991
Opened 2021-11-26 14:40 UTC by dITySoftware

# Make sure these boxes are signed before submitting your Pull Request -- thank you.

# Must haves
- [x] I have read and followed the contributing guide lines at https://github.com/ait-aecid/logdata-anomaly-miner/wiki/Git-development-workflow
- [x] Issues exist for this PR
- [x] I added related issues using the "Fixes #<issue-id>"-notations
- [x] This Pull-Requests merges into the "development"-branch

Fixes #833

# Submission specific

- [ ] This PR introduces breaking changes
- [ ] My change requires a change to the documentation
- [ ] I have updated the documentation accordingly
- [ ] I have added tests to cover my changes
- [ ] All new and existing tests passed

# Describe changes:
- Tested manually and the solution is working as expected and documented.

2021-11-29 13:17 UTC, whotwagner requested changes

2021-11-29 13:17 UTC, whotwagner commented on source/root/usr/lib/logdata-anomaly-miner/aminer/schemas/BaseSchema.yml
> +            'default': 1048576,  # 1 Megabyte
Let's make it 100Mb. So that we use max 500mb space for logs

2021-11-29 20:11 UTC, dITySoftware commented on source/root/usr/lib/logdata-anomaly-miner/aminer/schemas/BaseSchema.yml
> +            'default': 1048576,  # 1 Megabyte
Done.

2021-11-30 08:57 UTC, whotwagner approved these changes

2021-11-30 08:57 UTC, merged