Added rotation method for StreamPrinterEventHandler streams.
ait-aecid/logdata-anomaly-miner pull request #992
Opened 2021-11-26 19:57 UTC by dITySoftware

# Make sure these boxes are signed before submitting your Pull Request -- thank you.

# Must haves
- [x] I have read and followed the contributing guide lines at https://github.com/ait-aecid/logdata-anomaly-miner/wiki/Git-development-workflow
- [x] Issues exist for this PR
- [x] I added related issues using the "Fixes #<issue-id>"-notations
- [x] This Pull-Requests merges into the "development"-branch

Fixes #990

# Submission specific

- [ ] This PR introduces breaking changes
- [ ] My change requires a change to the documentation
- [ ] I have updated the documentation accordingly
- [ ] I have added tests to cover my changes
- [ ] All new and existing tests passed

# Describe changes:
-

2021-11-29 13:23 UTC, whotwagner requested changes

2021-11-29 13:23 UTC, whotwagner commented on source/root/usr/lib/logdata-anomaly-miner/aminer/AnalysisChild.py
> +                if event_handler.stream.name == "<stdout>":
please also add stderr

2021-11-29 20:52 UTC, dITySoftware commented on source/root/usr/lib/logdata-anomaly-miner/aminer/AnalysisChild.py
> +                if event_handler.stream.name == "<stdout>":
Done.

2021-11-30 09:49 UTC, whotwagner requested changes

2021-11-30 09:49 UTC, whotwagner commented on source/root/usr/lib/logdata-anomaly-miner/aminer/AnalysisChild.py
> +                event_handler.stream.close()
could we wrap a try around the close() and open() statements and print an error in case of an exception and terminate the aminer gracefully?

2021-12-01 11:52 UTC, whotwagner approved these changes

2021-12-01 11:52 UTC, merged